# Конфигурация политик enrichment для системы управления каналами
# [C7-ID: ENRICH-POLICY-001]

# ============================================================================
# ОБЩИЕ НАСТРОЙКИ
# ============================================================================

enrichment:
  # Включение/отключение enrichment
  enabled: true
  
  # Максимальное количество параллельных операций enrichment
  max_concurrent_operations: 5
  
  # Таймаут для операций enrichment (секунды)
  operation_timeout: 60
  
  # Максимальное количество попыток при ошибках
  max_retry_attempts: 3
  
  # Задержка между попытками (секунды)
  retry_delay_seconds: [5, 15, 60]

# ============================================================================
# CRAWL4AI ОБОГАЩЕНИЕ
# ============================================================================

crawl4ai:
  # Включение crawl4ai enrichment
  enabled: true
  
  # Триггеры для обогащения (теги, которые запускают crawl4ai)
  trigger_tags:
    - longread
    - research
    - paper
    - release
    - law
    - deepdive
    - analysis
    - report
    - study
    - whitepaper
  
  # Минимальное количество слов для обогащения
  min_word_count: 500
  
  # Максимальное количество токенов в день на пользователя
  max_tokens_per_day_per_user: 50000
  
  # Таймаут для crawl операций (секунды)
  timeout_seconds: 30
  
  # Максимальная длина URL для обогащения
  max_url_length: 2048
  
  # Ограничения на домены
  domain_restrictions:
    # Разрешённые домены (пустой список = все разрешены)
    allowed_domains: []
    
    # Запрещённые домены
    blocked_domains:
      - "example.com"
      - "test.com"
  
  # Настройки безопасности
  security:
    # Проверка robots.txt
    respect_robots_txt: true
    
    # Максимальная глубина редиректов
    max_redirects: 5
    
    # User-Agent для запросов
    user_agent: "TelegramAssistant/1.0 (Crawl4AI Bot)"
    
    # Задержка между запросами (секунды)
    request_delay: 1.0
  
  # Кеширование результатов
  caching:
    enabled: true
    
    # TTL кеша (дни)
    ttl_days: 7
    
    # Максимальный размер кеша (MB)
    max_cache_size_mb: 1000

# ============================================================================
# ТЕГИРОВАНИЕ
# ============================================================================

tagging:
  # Размер батча для тегирования
  batch_size: 10
  
  # Окно накопления для батчей (миллисекунды)
  batch_window_ms: 500
  
  # Провайдеры в порядке приоритета
  providers:
    - gigachat  # primary
    - openrouter  # fallback
    - local  # последний fallback
  
  # Настройки ретраев
  retry_attempts: 3
  backoff_seconds: [5, 15, 60]
  
  # Структурированный вывод (JSON)
  structured_output: true
  
  # Максимальное количество тегов на пост
  max_tags_per_post: 10
  
  # Минимальная уверенность в теге
  min_tag_confidence: 0.7
  
  # Категории тегов
  tag_categories:
    - tech
    - business
    - science
    - culture
    - politics
    - sports
    - finance
    - health
    - education
    - other

# ============================================================================
# ДЕДУПЛИКАЦИЯ
# ============================================================================

deduplication:
  # Включение дедупликации
  enabled: true
  
  # Алгоритм хеширования
  hash_algorithm: sha256
  
  # Пропускать посты с существующим хешем
  skip_if_hash_exists: true
  
  # Нормализация текста перед хешированием
  text_normalization:
    # Приведение к нижнему регистру
    lowercase: true
    
    # Удаление лишних пробелов
    trim_whitespace: true
    
    # Удаление трекинг-параметров из URL
    remove_tracking_params: true
    
    # Удаление эмодзи
    remove_emojis: false
    
    # Удаление HTML тегов
    remove_html_tags: true

# ============================================================================
# ЛИМИТЫ И КВОТЫ
# ============================================================================

limits:
  # Лимиты на пользователя
  per_user:
    # Максимальное количество постов для enrichment в день
    max_enrichment_per_day: 100
    
    # Максимальное количество токенов в день
    max_tokens_per_day: 100000
    
    # Максимальная длина текста для обработки (символы)
    max_text_length: 50000
  
  # Глобальные лимиты
  global:
    # Максимальное количество параллельных операций
    max_concurrent_operations: 50
    
    # Максимальная нагрузка на API (запросов в минуту)
    max_api_requests_per_minute: 1000
    
    # Максимальный размер очереди обработки
    max_queue_size: 10000

# ============================================================================
# МОНИТОРИНГ И МЕТРИКИ
# ============================================================================

monitoring:
  # Включение детального логирования
  detailed_logging: true
  
  # Логирование причин пропуска enrichment
  log_skip_reasons: true
  
  # Метрики производительности
  performance_metrics:
    # Время обработки операций
    operation_timing: true
    
    # Использование токенов
    token_usage: true
    
    # Успешность операций
    success_rates: true
  
  # Алерты
  alerts:
    # Алерт при высокой частоте ошибок
    high_error_rate_threshold: 0.1  # 10%
    
    # Алерт при превышении лимитов токенов
    token_limit_alert_threshold: 0.8  # 80% от лимита
    
    # Алерт при длинной очереди
    queue_size_alert_threshold: 1000

# ============================================================================
# КОНФИГУРАЦИЯ ПРОВАЙДЕРОВ
# ============================================================================

providers:
  # GigaChat настройки
  gigachat:
    enabled: true
    priority: 1
    model: "GigaChat:latest"
    max_tokens: 4000
    temperature: 0.1
    timeout: 30
    # Ограничение: 1 поток одновременных запросов
    max_concurrent_requests: 1
    request_queue_size: 10
    
  # OpenRouter настройки
  openrouter:
    enabled: true
    priority: 2
    model: "anthropic/claude-3-haiku"
    max_tokens: 4000
    temperature: 0.1
    timeout: 30
    
  # Локальные модели
  local:
    enabled: false
    priority: 3
    model: "local/llama2"
    max_tokens: 2000
    temperature: 0.1
    timeout: 60

# ============================================================================
# НАСТРОЙКИ КАЧЕСТВА
# ============================================================================

quality:
  # Минимальное качество для принятия результатов
  min_quality_score: 0.7
  
  # Проверка качества результатов
  quality_validation: true
  
  # Фильтрация низкокачественных результатов
  filter_low_quality: true
  
  # Порог для фильтрации
  quality_threshold: 0.5

# ============================================================================
# НАСТРОЙКИ ПРОИЗВОДИТЕЛЬНОСТИ
# ============================================================================

performance:
  # Размер пула соединений
  connection_pool_size: 20
  
  # Таймаут соединения
  connection_timeout: 10
  
  # Максимальное время жизни соединения
  max_connection_lifetime: 3600
  
  # Кеширование соединений
  connection_caching: true
  
  # Асинхронная обработка
  async_processing: true
  
  # Параллельная обработка батчей
  parallel_batch_processing: true
