#!/bin/bash
# Помощь по получению telegram_id для каналов

echo "📋 Как получить telegram_id для каналов про пиво"
echo ""
echo "Способ 1: Через бота @userinfobot (самый простой)"
echo "  1. Откройте Telegram"
echo "  2. Найдите бота @userinfobot"
echo "  3. Отправьте ссылку на канал:"
echo "     - https://t.me/beer_for_all"
echo "     - https://t.me/beer_by"
echo "     - https://t.me/prostopropivo"
echo "  4. Бот вернет Channel ID (отрицательное число, например: -1001234567890)"
echo ""
echo "Способ 2: Через бота @getidsbot"
echo "  1. Откройте Telegram"
echo "  2. Найдите бота @getidsbot"
echo "  3. Отправьте ссылку на канал"
echo ""
echo "Способ 3: Через Telegram Desktop"
echo "  1. Откройте канал в Telegram Desktop"
echo "  2. View -> Statistics -> Channel ID"
echo ""
echo "После получения ID выполните:"
echo "  ./scripts/update_beer_channels_manual.sh <beer_for_all_id> <beer_by_id> <prostopropivo_id>"
echo ""
echo "Пример:"
echo "  ./scripts/update_beer_channels_manual.sh -1001234567890 -1001234567891 -1001234567892"
