name: Guard
on: [pull_request]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # [C7-ID: dev-mode-010] Context7 best practice: используем Python инструменты вместо Node.js
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y docker.io
          pip install jsonschema
      - run: bash scripts/compose-guard.sh
      - run: python3 scripts/env-check.py || true
